import { RoadmapCard } from '../types';

export const INITIAL_ROADMAP: RoadmapCard[] = [
  {
    id: 'card-s0-1',
    sprint: 'sprint-0',
    title: 'Zero-Bloat Repo & Guardrails',
    description: 'Establish repository strictly under 10MB, configure .gitignore, single main branch, and Vercel CSP headers.',
    category: 'Architecture',
    status: 'verified',
    priority: 'Critical',
    securityCheckpoint: 'Exclude .env, logs, build artifacts, enforce CSP in vercel.json.',
    a11yCheckpoint: 'Establish high-contrast dark palette (contrast >= 7:1).',
    checklist: [
      { id: 'c1', text: 'Configure strict .gitignore (node_modules, dist, .env)', completed: true },
      { id: 'c2', text: 'Set up single main branch with zero feature PR bloat', completed: true },
      { id: 'c3', text: 'Enforce CSP and security headers in vercel.json', completed: true },
    ],
  },
  {
    id: 'card-s0-2',
    sprint: 'sprint-0',
    title: 'Modular Type System & Linting',
    description: 'Set up TypeScript strict mode, JSDoc typings, ESLint rules with zero any-types.',
    category: 'Architecture',
    status: 'verified',
    priority: 'High',
    securityCheckpoint: 'Type-safe contracts for all gene mutations and evaluator states.',
    a11yCheckpoint: 'HTML lang attribute and meta tags in index.html.',
    checklist: [
      { id: 'c4', text: 'Define Gene, Mutation, Roadmap, and Judge interfaces', completed: true },
      { id: 'c5', text: 'Zero TypeScript compiler errors in noEmit check', completed: true },
      { id: 'c6', text: 'Clean ESLint passes with zero warnings', completed: true },
    ],
  },
  {
    id: 'card-s1-1',
    sprint: 'sprint-1',
    title: 'Interactive SVG Genome Visualizer',
    description: 'Render double-helix DNA strand with sine-wave coordinate mapping, codons, and interactive gene inspection.',
    category: 'Architecture',
    status: 'verified',
    priority: 'Critical',
    securityCheckpoint: 'SVG nodes generated dynamically via mathematical coords, no innerHTML.',
    a11yCheckpoint: 'ARIA roles role="graphics-document" and keyboard selectable genes.',
    checklist: [
      { id: 'c7', text: 'Calculate 3D rotating sine wave coordinates', completed: true },
      { id: 'c8', text: 'Interactive gene node selection with glow highlights', completed: true },
      { id: 'c9', text: 'Detailed codon breakdown (A-T, G-C nucleotide base pairs)', completed: true },
    ],
  },
  {
    id: 'card-s1-2',
    sprint: 'sprint-1',
    title: 'AI Mutation Engine & Diff Viewer',
    description: 'Mutation laboratory offering framework swaps, Google API integrations, and security boosters with before/after diff.',
    category: 'Technology',
    status: 'verified',
    priority: 'High',
    securityCheckpoint: 'Strict mutation validation prevents invalid codon states.',
    a11yCheckpoint: 'Screen reader announcement upon mutation application.',
    checklist: [
      { id: 'c10', text: 'Curate 4 specialized hackathon architectural mutations', completed: true },
      { id: 'c11', text: 'Live visual diff previewing codon and tech changes', completed: true },
      { id: 'c12', text: 'Real-time score recalculation upon applying mutations', completed: true },
    ],
  },
  {
    id: 'card-s2-1',
    sprint: 'sprint-2',
    title: 'Google Cloud Services Integration',
    description: 'Quad-service Google suite: Firebase Auth/Sync, Google Sheets CSV Export, Cloud Vision UI Auditor, Maps Geo-Radar.',
    category: 'Technology',
    status: 'verified',
    priority: 'Critical',
    googleApi: 'Firebase',
    securityCheckpoint: 'Mask sensitive API keys, simulate secure Firestore transactions.',
    a11yCheckpoint: 'Accessible modal dialogs with focus trapping and ESC-to-close.',
    checklist: [
      { id: 'c13', text: 'Firebase auth state and Firestore genome backup', completed: true },
      { id: 'c14', text: 'One-click Google Sheets export for roadmap & judge scores', completed: true },
      { id: 'c15', text: 'Google Cloud Vision UI diagram and wireframe auditor', completed: true },
      { id: 'c16', text: 'Google Maps interactive team node locator', completed: true },
    ],
  },
  {
    id: 'card-s2-2',
    sprint: 'sprint-2',
    title: 'Zero-Dependency XSS Sanitizer Sandbox',
    description: 'Interactive security playground proving anti-XSS protection, HTML entity encoding, and secret key masking.',
    category: 'Guardrails',
    status: 'verified',
    priority: 'Critical',
    securityCheckpoint: 'Neutralizes <script>, javascript:, and event handlers (onload, onerror).',
    a11yCheckpoint: 'High contrast badges and accessible form input controls.',
    checklist: [
      { id: 'c17', text: 'Implement escapeHtml and sanitizeInput algorithms', completed: true },
      { id: 'c18', text: 'Interactive testing playground with sample attack payloads', completed: true },
      { id: 'c19', text: 'Secret key masking protecting environment variables', completed: true },
    ],
  },
  {
    id: 'card-s3-1',
    sprint: 'sprint-3',
    title: 'Judge Mode 99/100 Rubric Engine',
    description: 'Multi-pillar AI Judge scoring simulator evaluating Code Quality, Security, Accessibility, Testing, and Google Services.',
    category: 'Checkpoints',
    status: 'verified',
    priority: 'Critical',
    securityCheckpoint: 'Transparent criteria auditing without hardcoded falsified checks.',
    a11yCheckpoint: 'Accessible progress meters and status badges with role="meter".',
    checklist: [
      { id: 'c20', text: 'Implement 5 rubric pillars scored out of 20 each', completed: true },
      { id: 'c21', text: 'Dynamic score calculation scaling to 99/100 benchmark', completed: true },
      { id: 'c22', text: 'Automated verdict generation (Accepted for Podium)', completed: true },
    ],
  },
  {
    id: 'card-s3-2',
    sprint: 'sprint-3',
    title: 'Vitest Unit & Component Test Suite',
    description: 'Comprehensive test coverage across sanitization routines, genome algorithms, scoring engine, and React UI mounts.',
    category: 'Checkpoints',
    status: 'verified',
    priority: 'Critical',
    securityCheckpoint: 'Automated test suite ensures zero runtime errors before deployment.',
    a11yCheckpoint: 'Tests verify presence of ARIA attributes and labels.',
    checklist: [
      { id: 'c23', text: 'Unit tests for sanitizeInput and escapeHtml', completed: true },
      { id: 'c24', text: 'Unit tests for calculateGenomeFitness and DNA coords', completed: true },
      { id: 'c25', text: 'Unit tests for evaluateProjectRubric thresholds', completed: true },
      { id: 'c26', text: 'App component integration render test', completed: true },
    ],
  },
];
